#!/bin/sh

source $(dirname $0)/panel_config

volume(){
    VOLUME=$(pulseaudio-ctl full-status | awk '{split($0, array, " ")} END{print array[1]}')
    MUTE=$(pulseaudio-ctl full-status | awk '{split($0, array, " ")} END{print array[2]}')
    if [ "$MUTE" == "yes" ]; then
        echo "%{F$RED_COLOR A:pulseaudio-ctl mute:}$(printf '%b' "\ue04f") $VOLUME%%{A F-}"
    else 
	echo "%{F$BLUE_COLOR A:pulseaudio-ctl mute:}$(printf '%b' "\ue05d")%{F-} $VOLUME%%{A}"
    fi
}

mpd(){
    STATUS=$(mpc current)
    echo "%{F$BLUE_COLOR A:mpc toggle: A3:mpc stop:}$(printf '%b' "\ue05c")%{F-} $STATUS%{A A}"
}


wifi_ssid(){
    NAME=$(iwconfig wlp3s0b1 | grep 'ESSID:' | awk '{print $4}' | sed 's/ESSID://g' | sed 's/"//g')
    if [ "$NAME" == "off/any" ]; then
        echo "%{F$RED_COLOR}$(printf '%b' "\ue048")%{F-} no conn"
    else echo "%{F$WIFI_COLOR}$(printf '%b' "\ue048")%{F-} $NAME"
    fi
}

battery() {
    BATTERY=$(~/bin/battery.sh)
    echo "%{F$BAT_COLOR}$(printf '%b' "\ue041")%{F-} $BATTERY"
}

load_avg() {
    AVGLOAD=$(cut -d " " -f 1-3 /proc/loadavg)
    echo "%{F$BLUE_COLOR}$(printf '%b' "\ue021")%{F-} $AVGLOAD"
}


while :; do
    echo "S$(mpd)%{r}$(battery) $SEP $(wifi_ssid) $SEP $(volume)  %{B$YELLOW_COLOR}  %{F$WIFI_COLOR}$(printf '%b' "\ue01f") %{F$BACKGROUND_COLOR} $(date +'%A, %b %d')  %{B$FOREGROUND_COLOR} %{F$WIFI_COLOR} $(printf '%b' "\ue016") %{F$BACKGROUND_COLOR} $(date +'%H:%M')  %{B F-}"
    sleep 2
done
